apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: qotd-nfdn7081
  name: qotd-nfdn7081
spec:
  port:
    targetPort: 10000-tcp
  to:
    kind: Service
    name: qotd-nfdn7081
    weight: 100
